table acteurs_tabel
	lineageTag: 91e22050-f19b-4e28-98c2-31d1f2938f92

	column actor_name
		dataType: string
		lineageTag: 3beb2d1e-c886-4a1b-baf2-062b58bcf3da
		summarizeBy: none
		sourceColumn: actor_name

		annotation SummarizationSetBy = Automatic

	column actor_id
		dataType: int64
		formatString: 0
		lineageTag: f8467b18-49ca-4623-9123-fde000d9a1cc
		summarizeBy: sum
		sourceColumn: actor_id

		annotation SummarizationSetBy = Automatic

	partition acteurs_tabel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Gebruiker\OneDrive - NHL Stenden\Documenten\test\acteurs_tabel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"actor_name", type text}, {"actor_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

