table films_tabel
	lineageTag: 9aa53fcf-d18d-438e-9c7e-933d7ad9a8df

	column film_id
		dataType: int64
		formatString: 0
		lineageTag: 09ec195f-e9e4-4907-9cdf-08765b34d4e1
		summarizeBy: none
		sourceColumn: film_id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 06b2bfb2-6ca9-4eb3-a320-0a3b3df78daa
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column title_year
		dataType: int64
		formatString: 0
		lineageTag: a165585d-94ca-4668-ac04-629876e866b5
		summarizeBy: sum
		sourceColumn: title_year

		annotation SummarizationSetBy = Automatic

	column budget
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 6f490f76-a30c-47f5-b1cb-21b87c5af383
		summarizeBy: sum
		sourceColumn: budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column gross
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: d9a0e6de-c75d-43a6-9d22-cd7213ddd2b8
		summarizeBy: sum
		sourceColumn: gross

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column roi
		dataType: double
		lineageTag: 66378d56-e56b-4113-aa6f-f4241def29d5
		summarizeBy: sum
		sourceColumn: roi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column mpa
		dataType: string
		lineageTag: 75260037-58b1-474c-9dc8-c42a97a866c9
		summarizeBy: none
		sourceColumn: mpa

		annotation SummarizationSetBy = Automatic

	column duration
		dataType: string
		lineageTag: fe5d54cf-1efb-42d4-b9ba-995f11579c87
		summarizeBy: none
		sourceColumn: duration

		annotation SummarizationSetBy = Automatic

	column méta_score
		dataType: string
		lineageTag: e5113093-73a8-46d4-b80a-3623904bc8d2
		summarizeBy: none
		sourceColumn: méta_score

		annotation SummarizationSetBy = Automatic

	column rating
		dataType: double
		lineageTag: ac0be8f0-c3f2-4c5d-8e5d-1d77153faf60
		summarizeBy: sum
		sourceColumn: rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column director_name
		dataType: string
		lineageTag: c9b0a29d-d2f7-41cb-918a-28f94fa03630
		summarizeBy: none
		sourceColumn: director_name

		annotation SummarizationSetBy = Automatic

	column actor_1_name
		dataType: string
		lineageTag: 260b26ba-e26f-447e-8152-e8509b27be3d
		summarizeBy: none
		sourceColumn: actor_1_name

		annotation SummarizationSetBy = Automatic

	partition films_tabel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Gebruiker\OneDrive - NHL Stenden\Documenten\test\films_tabel.csv"),[Delimiter=",", Columns=13, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"film_id", Int64.Type}, {"title", type text}, {"title_year", Int64.Type}, {"budget", Currency.Type}, {"gross", Currency.Type}, {"roi", Currency.Type}, {"mpa", type text}, {"duration", type text}, {"méta_score", type text}, {"rating", type number}, {"director_name", type text}, {"actor_1_name", type text}, {"duration_min", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type", {"budget"}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Removed Errors", {"gross"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Errors1",{"duration_min"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"roi", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

