table film_genres
	lineageTag: 2b4a620b-6ce2-45d2-98a4-bcc5df367f34

	column film_id
		dataType: int64
		formatString: 0
		lineageTag: e3a7a166-0274-4489-a2fe-1d21e8089b52
		summarizeBy: none
		sourceColumn: film_id

		annotation SummarizationSetBy = Automatic

	column genre_id
		dataType: int64
		formatString: 0
		lineageTag: cabb2a64-e05f-470d-b2e0-fe5dcae9de84
		summarizeBy: none
		sourceColumn: genre_id

		annotation SummarizationSetBy = Automatic

	partition film_genres = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Gebruiker\OneDrive - NHL Stenden\Documenten\test\film_genres.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"film_id", Int64.Type}, {"genre_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

