table film_acteurs
	lineageTag: cb2843ef-e435-4b18-ae7e-29318aa896da

	column film_id
		dataType: int64
		formatString: 0
		lineageTag: 19720429-b025-42b0-bbd1-8dd8d41cd001
		summarizeBy: sum
		sourceColumn: film_id

		annotation SummarizationSetBy = Automatic

	column actor_name
		dataType: string
		lineageTag: 2385e358-66f5-4444-a404-4ddd041eecbe
		summarizeBy: none
		sourceColumn: actor_name

		annotation SummarizationSetBy = Automatic

	partition film_acteurs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Gebruiker\OneDrive - NHL Stenden\Documenten\test\film_acteurs.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"film_id", Int64.Type}, {"actor_name", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

