table regisseurs_tabel
	lineageTag: 75198dc9-1013-489d-b7a7-404f81d50cc6

	column director_name
		dataType: string
		lineageTag: 8c2ef4d2-934b-471a-9c6e-346ad8e89cfe
		summarizeBy: none
		sourceColumn: director_name

		annotation SummarizationSetBy = Automatic

	column director_id
		dataType: int64
		formatString: 0
		lineageTag: e78be03e-55ff-4669-9dcb-7496b2ccbf37
		summarizeBy: none
		sourceColumn: director_id

		annotation SummarizationSetBy = Automatic

	partition regisseurs_tabel = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Gebruiker\OneDrive - NHL Stenden\Documenten\test\regisseurs_tabel.csv"),[Delimiter=",", Columns=2, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"director_name", type text}, {"director_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

